#!/bin/sh /etc/rc.common

START=20
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/true
    procd_close_instance
    echo host > /sys/class/udc/ci_hdrc.0/device/driver/ci_hdrc.0/role
}

stop_service() {
    echo device > /sys/class/udc/ci_hdrc.0/device/driver/ci_hdrc.0/role
}
